apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vault-ui
spec:
  entryPoints:
    - internalhttps
  routes:
    - kind: Rule
      match: {{.Values.hostPrefixRegex}} && PathPrefix(`/ui`)
      services:
        - kind: Service
          name: vault-ui
          namespace: {{.Release.Namespace}}
          passHostHeader: true
          port: 8200